version: "3.8"
services:
  moodle:
    build:
      context: ./docker
      args:
        TARGETPLATFORM: linux/amd64
    # command: ['cat', '/etc/apache2/sites-enabled/000-default.conf']

    environment:
      DB_TYPE: mariadb
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: "m@0dl3ing"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '8080:80'
    depends_on: 
      - mariadb
      - redis
  redis:
    image: redis:6
  mariadb:
    image: mariadb:10.5
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_per_table=On
              --wait-timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle
    ports:
      - 3306:3306
