version: "3.8"
services:
  webserver:
    build:
      context: ./
    environment:
      MOODLE_DOCKER_DB_TYPE: mariadb
      MOODLE_DOCKER_DB_HOST: mariadb
      MOODLE_DOCKER_DB_NAME: moodle
      MOODLE_DOCKER_DB_USER: moodle
      MOODLE_DOCKER_DB_PASS: "m@0dl3ing"
      MOODLE_DOCKER_WEB_HOST: http://localhost:5005
    ports:
      - '5005:80'
    depends_on: 
      - mariadb
      - redis
      - mailhog
  redis:
    image: redis:6
  mariadb:
    image: mariadb:10.5
    command: >
              --character-set-server=utf8mb4
              --collation-server=utf8mb4_bin
              --innodb_file_per_table=On
              --wait-timeout=28800
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle
  
  mailhog:
    image: mailhog/mailhog